### ISSUE TITLE
standard star for MOS data 

### ISSUE THREAD

**Issue by caiz12** [PYPIT/PYPIT#113]
For MOS mask data, people may not take standard star. If one does not have 
standard star, then one may need to do the following: 

commented out two lines which cause errors if we don't have standard stars: 

(1)  in arsort.py, comments out lines 472 and line 473: 

  # if ftag[ft] == 'standard' and argflag['reduce']['fluxcalibrate']:
  #     msgs.error("Unable to continue without more {0:s} frames".format(ftag[ft]))

(2)  in arsciexp.py, line 48: 

   comment   # self._idx_std = spect['standard']['index'][snum]

**Comment by rcooke-ast** [comment]
Alternatively, instead of commenting out the code, the user can set the following keywords:

`reduce fluxcalibrate False` (in the .pypit file, before the data are read in)

and/or

```
spect read
  standard number 0
spect end
```

Could you please check these two possibilities and confirm they work as intended with your setup (i.e. without commenting out the code)?

Thanks!

**Comment by profxj** [comment]
And then add documentation in the more_docs branch on running. PYPIT and also
add the keywords and a short description to the setup.rst file.  Thanks.

**Comment by caiz12** [comment]
I just tried Ryan's solution and it perfectly works ! Thanks !
