### ISSUE TITLE
1d coadding

### ISSUE THREAD

**Issue by tiffanyhsyu** [PYPIT/PYPIT#123]
In regards to 1d coadding:

Option 1: Ryan, I remember you mentioned that you know of someone who has a 1d coadding code that we could implement into PYPIT. I forget who it was, X says maybe Michael Murphy at Swinburne?

Option 2: Implement Low Redux's version of 1d coadding into PYPIT

**Comment by rcooke-ast** [comment]
Indeed - Michael Murphy has developed a code (in c, with pgplot) called UVES_popler. As the name suggests, it was originally written for UVES data, but has since been expanded to include other data reduction products.  I've not seen/used a better package for coadding spectra, but it can be quite laborious. I don't think we need to worry about development here, UVES_popler will be changed to read in our reduced data, for those that want to manually combine their data.

I'm all for option 2. We need to provide a coadding option for our package, and the LowRedux one is solid, and has been extensively tested/developed.

**Comment by tiffanyhsyu** [comment]
I am working on adding the 1d coadding option!

**Comment by profxj** [comment]
Implemented in PR #153 

Note that this passes all tests now (must have been fixed
in astropy v1.3).
