### ISSUE TITLE
Loop on setup in ARMLSD?

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#156]
Now that a .setup file has become integral to the data reduction,
I propose a refactor where ARMLSD loops on setup and then 
science exposure as opposed to looping on science exposure alone.

This could then allow one to strip most of the Masters code out of
ScienceExposure and likely into MasterFrames.  I can't see any obvious
downside, but @rcooke-ast has thought much more about this.

This would also further separate calibration processing from object extraction.

**Comment by profxj** [comment]
@adwasser should also comment on pros/cons for parallelization.

**Comment by rcooke-ast** [comment]
I suppose this depends on how we proceed with the suggestion made in the description of PR #150 ("limit each working directory to one .setup file").

I think it's a good idea in principle to loop over setup, especially if we decide to bulk reduce data taken with multiple setups using a single PYPIT file.

At the moment, for every science frame, the ScienceExposure class stores (copies) each master calibration frame. My main intention with the MasterFrames code is to avoid saving duplicate master calibration frames in the ScienceExposure class. Instead, the ScienceExposure class should store the index where it can find a master calibration frame in the MasterFrames class. See also my first comment in PR #108 (and for reference, Issue #106).

So, I agree that the generation of master calibration frames can go in the MasterFrames class. I think this could have significant advantages on the multiprocessing front, as the ScienceExposure class won't need to carry around additional functions and master calibration frames.

**Comment by profxj** [comment]
Ok, I think we are going to make this move.  I'll lead
the charge.  

And, to be clear, I envision one .setup file per *instrument*.

The key issue (in my mind) is to avoid over-writing MasterFrame
files on disk.  But there are some lesser issues too.

**Comment by adwasser** [comment]
I'm going to tentatively say that sounds fine for multiprocessing.  The basic idea is that a ScienceExposure instance has references to the slit traces, and so it can split a given 2d-array into a list of slits, which is then mapped out to some function, and possibly joined together at the end.  That doesn't care about whether the input array is stored in the ScienceExposure or is passed in from somewhere else.   But if the functions to be parallelized live inside the MasterFrame class and don't have a reference to the ScienceExposure, then the traces would have to be passed in somewhere else.

For the master frame generation, the parallelized functions will have to be fairly low-level, since we want to avoid writing to the same file from multiple threads.  (Or we could consider saving master frames at the level of slits?  too much file I/O?).  But for operations that just involve reading and calculating (flat fielding, object trace, extraction), it may be possible to lump it all into one big function that maps slits to 1d spectra.

**Comment by profxj** [comment]
After starting to sketch out how this might work, I can see it won't.  :)

I have, however, decided to improve the naming and organization of setups
and master frames.  Stay tuned..
