### ISSUE TITLE
[WARNING] :: Matching criteria '' not supported for this instrument

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#213]
I'm running on the latest version of the master branch. I ran,

 `pypit_setup <PATH> lris_blue`

When I got the warning, "[WARNING] :: Matching criteria '' not supported for this instrument".

I don't know what this warning is referring to. Can somebody clarify?

**Comment by rcooke-ast** [comment]
PYPIT tries to match certain frames to a science frame by using some keywords. In this case, the keyword appears to be an empty string. Were all of your calibrations correctly assigned?

Having just looked at the code, I think this warning is occurring because there are some frames that do not need to be matched to the science frames (e.g. pinhole frames). I'll submit a quick PR that should fix this issue, but perhaps you can check it for me, since I'm unable to reproduce this warning with any of the example data I have to hand.

**Comment by AlexaVillaume** [comment]
> PYPIT tries to match certain frames to a science frame by using some keywords. In this case, the keyword appears to be an empty string. Were all of your calibrations correctly assigned?

My flat fields never get assigned correctly when I first run pypit_setup, I always have to augment the .pypit file for them to be recognized.

> Having just looked at the code, I think this warning is occurring because there are some frames that do not need to be matched to the science frames (e.g. pinhole frames). I'll submit a quick PR that should fix this issue, but perhaps you can check it for me, since I'm unable to reproduce this warning with any of the example data I have to hand.

Yep, I'll take a look now.

**Comment by AlexaVillaume** [comment]
Fixed in #215
