### ISSUE TITLE
Kast data reduction

### ISSUE THREAD

**Issue by marijana777** [PYPIT/PYPIT#219]
After pypit_setup the file kast_red_2017-May-09.sorted is not generated. 

pypit_setup /home/user/data/r kast_red 
pypit_setup --custom /home/user/data/r kast_red 

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/pypit_setup", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/user/PYPIT/bin/pypit_setup", line 17, in <module>
    setup.main(args)
  File "/home/user/PYPIT/pypit/scripts/setup.py", line 114, in main
    all_setups, all_setuplines, all_setupfiles = arsort.load_sorted(sorted_file)
  File "/home/user/PYPIT/pypit/arsort.py", line 1081, in load_sorted
    with open(sorted_file,'r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: './kast_red_2017-May-09.sorted'

**Comment by profxj** [comment]
Please confirm that you have run successfully the PYPIT development suite.

**Comment by marijana777** [comment]
PYPIT development suite does not give any errors. 

~/PYPIT-development-suite$ ./pypit_test kast
Output directory exists.
Running pypit on kast_red_600_7500_d55.pypit --- 
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
01.DSENSOR 0 DSENSOR
2k x 4k Hamamatsu Ret 400x1200
Wrote ./kast_blue_2017-May-09.pypit
Wrote ./kast_blue_setup_A/kast_blue_setup_A.pypit
[INFO]    ::   Found 12 trace frames for J1217p3905 (0 are required)
[INFO]    :: Science frames successfully matched to calibration frames
[WARNING] :: Over-writing existing .setups file
[INFO]    :: Setup is complete. Change 'run setup' to False to continue with data reduction
[INFO]    :: Inspect the .setups file: ./kast_blue_2017-Feb-10.setups
[INFO]    :: Setup complete
[INFO]    :: Data reduction execution time: 1.07s
[INFO]    :: Loading the input file
[INFO]    :: Found 27 raw data frames
[INFO]    :: Input file loaded successfully
Running pypit on kast_blue_setup_A.pypit ---

**Comment by profxj** [comment]
Try entering the REDUX directory and doing your individual steps.
Anyhow, you haven't provided enough information for me to identify
or reproduce the bug.  Please explore yourself for now.

**Comment by tiffanyhsyu** [comment]
I've come across this error before! At least in the times I've encountered it, it was because my calibration and/or science frames were not identified correctly by PYPIT.

After running pypit_setup /home/user/data/r kast_red, you should check that your files have been sorted correctly. I think the best way to do this is to open up the .lst file and check specifically which frames were misidentified (you'll have to do this eventually to overwrite the auto-IDs by PYPIT), but a quick way is to look at the messages printed by PYPIT, for example:

[INFO]    :: Found 11 pixelflat frames
[INFO]    :: Found 11 trace frames
[INFO]    :: Found 0 unknown frames
[INFO]    :: Found 11 bias frames
[INFO]    :: Found 0 standard frames
[INFO]    :: Found 0 dark frames
[INFO]    :: Found 24 arc frames
[INFO]    :: Found 0 science frames
[INFO]    :: Found 0 pinhole frames

In this case, PYPIT thinks I have 0 standard and science frames, and 24 arcs, which isn't right. You'll have to correct these misidentifications by manually specifying in the .pypit file what each frame is, like 'set science r30.fits'. This goes between the 'spect read' and 'spect end' section (and there should be more detailed information on how to do this in the documentation).

After you make all necessary changes to the .pypit file, you'll have to rerun pypit_setup:
pypit setup --pypit_file name_of_file.pypit kast_red

And then you can do the step: pypit_setup --custom /home/user/data/r kast_red, which will create a setup-specific directory.

And all should be good!
