### ISSUE TITLE
Not all pypit scripts in path?

### ISSUE THREAD

**Issue by AlexaVillaume** [PYPIT/PYPIT#221]
The scripts coadd_1dspec.py and show_twod.py don't seem to be in my python path (the script name doesn't tab complete and if I type it out it isn't recognized as a command), is this the case for other people? 

Also, why is the 2D script refereed to as show_2dspec in the documentation but it's show_twod in the code?

**Comment by AlexaVillaume** [comment]
From Ryan via Tiffany this is an issue with cython and there are two things to try

1. in ~/PYPIT/, run: python setup.py develop
2. in ~/PYPIT/pypit, run: source compile_arcy.sh 

I tried the first and it worked. It'd be good to add a Troubleshooting section to the Documentation, or even with each major component of PYPIT. I'll try to get to that this week.

**Comment by rcooke-ast** [comment]
Hi Alexa,

I don't think the second step is needed anymore, since the first step will also compile the cython code. The main point to take away is, every time you get a new copy of the code, you need to "install" it, by executing the command you list in 1. above:

`python setup.py develop`

note: you could instead do:
`python setup.py install`

Thanks for pointing out that this is missing!
