### ISSUE TITLE
Flat normalization in armlsd

### ISSUE THREAD

**Issue by profxj** [PYPIT/PYPIT#257]
I believe I have identified a 'bug' in that if one doesn't
explicitly specify

``` reduce slitprofile perform true ```
in armlsd (this may be the default in armed)
then the flat isn't normalized, i.e. the slit_profile is all ones.

**Comment by rcooke-ast** [comment]
I think that's right, yes. I had implemented it like this since I didn't think it was necessary to calculate the slit profile for longslit. If you think this is invalid, then we should change the default option. The default option for ARMED is True.

But, I think the spectral distribution is still normalized, right? It should only have been the (spatial) slit profile that wasn't taken into account. At least that's what I had intended.

**Comment by profxj** [comment]
Right you were.  I was getting hit by a poorly defined left edge
of the slit.
