### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by jhennawi** [PYPIT/PYPIT#358]
Hi All, 

Every time I want to find the main multi-slit driver routine it takes me about 15 minutes to locate the file. Granted I don't use it very often since I'm stuck in developer land. 

To be blunt:  arms.py is a useless name in my opinion. Do we have a character limit on filenames?

I'd suggest

multislit_driver.py

or ar_multislit_driver.py

Or something more informative. This piece of feedback could be applied to many of our filenames. 

Can we discuss our naming convention moving forward? 

Thanks, 
Joe

**Comment by profxj** [comment]
I think a fresh look at our naming schema is an excellent idea!  And
it would be an excellent opportunity for @jhennawi  to introduce himself
to PYPIT.  So I am assigning it to you.

As for ```arms.py```, it would seem impossible for you to be unaware
of its presence if you had paid attention to any of the 10 PR's that I
have recently generated, each of which edited it substantially.  I worry
that you have kept a blind-eye to all of my recent efforts.

Anyhow, you could also have found it in t<30s by doing:

1.  Returning to any of those PR's, e.g.

https://github.com/PYPIT/PYPIT/pull/343

or 

2.  Using the CTRL+Left-click option in PyCharm, e.g.

Go to the ```biasframe.py``` module

Use CTRL+Left-click on the get_msbias() method
This is a very good trick to know.  Especially for 
negotiating any repository that you are unfamiliar with.

**Comment by rcooke-ast** [comment]
Agreed - Can I add, that I think this is best discussed as a PR, not an issue, because we can comment and discuss the renaming of each filename itself.

The original naming scheme was when the organisation of the files was non existent, and all codes relevant to the reduction were prefixed with `ar` so they were grouped together. Since it's first creation, @profxj has done a great job reorganising the file structure, and it's due time to remove the `ar` prefix, and rename files appropriately.

All that said, I'm afraid that I can't see any better name for `arms.py` and `armed.py`. These are the names of the reduction pipelines for long/multislit and echelle (respectively).

Anyway, let's close the issue, and address as a PR.
