### ISSUE TITLE
Include a barycentric velocity correction

### ISSUE THREAD

**Issue by rcooke-ast** [PYPIT/PYPIT#80]
As titled  ;-)

**Comment by rcooke-ast** [comment]
Perhaps it would be easiest to port the following JAVA code:

[Barycentric Velocity Correction](http://adsabs.harvard.edu/abs/2016arXiv160804340M)

**Comment by profxj** [comment]
jxp> From xavier@ucolick.org Sat Aug 20 17:21:45 2016
jxp> From: "J. Xavier Prochaska" <xavier@ucolick.org>
jxp> Subject: Baryocentric
jxp> Date: Sat, 20 Aug 2016 08:21:39 -0700
jxp> To: mathar@mpia.de
jxp> 
jxp> Is there any possibility that you (or someone else)
jxp> will be providing a Python version of your Java based code?

I will not try it, ... I have no use case for it. There is likely
somewhere Python code that is doing almost the same thing, because
the application is not at all new, see e.g. https://pythonhosted.org/PyTPM/ ;
but I am not aware of any python implementation that mixes
ephemerides, the IERS bulletin and the Earth rotation.

Instead of porting the code it might be easier to start
from scratch with the python reader in https://pypi.python.org/pypi/EphemPy
and the SOFA interface in https://pypi.python.org/pypi/pysofa
(which of course is not up-to-date with respect to leap seconds...)
or https://pypi.python.org/pypi/erfa_python/2016.06.11 
or https://pythonhosted.org/Astropysics/coremods/coords.html

**Comment by rcooke-ast** [comment]
Thanks for sharing this communication! That is definitely the best way to proceed. For record, the CERES routines perform a barycentric velocity:

[arXiv paper](https://arxiv.org/abs/1609.02279)
[GitHub code](https://github.com/rabrahm/ceres)

**Comment by rcooke-ast** [comment]
Just found out that astropy apparently has this functionality:

[astropy barycentric velocity correction](https://gist.github.com/StuartLittlefair/5aaf476c5d7b52d20aa9544cfaa936a1)

**Comment by rcooke-ast** [comment]
Implemented in PR #190
